server:
  port: 8080
spring:
  dubbo:
    application:
      id: demo-dubbo
      name: demo-dubbo
    registry:
      address: zookeeper://127.0.0.1:2181
    protocols:
      rmi:
        id: rmi
        name: rmi
        port: 20880
        status: server
      dubbo:
        id: dubbo
        name: dubbo
        port: 20881
        status: server
    scan: com.you.comm.service